export const WIDGET_CREATING = 'WIDGET_CREATING'
export const WIDGET_CREATE_SUCCESS = 'WIDGET_CREATE_SUCCESS'
export const WIDGET_CREATE_ERROR = 'WIDGET_CREATE_ERROR'

export const WIDGET_REQUESTING = 'WIDGET_REQUESTING'
export const WIDGET_REQUESTING_SUCCESS = 'WIDGET_REQUESTING_SUCCESS'
export const WIDGET_REQUESTING_ERROR = 'WIDGET_REQUESTING_ERROR'